stages:
  convert_data:
    cmd: python src/utils/xml2csv.py data/data.xml data/data.csv
    deps:
    - data/data.xml
    - src/utils/xml2csv.py
    outs:
    - data/data.csv
  process_data:
    cmd: python src/utils/process_data.py data/data.csv data/processed_data.csv
    deps:
    - data/data.csv
    outs:
    - data/processed_data.csv
