stages:
  convert_data:
    cmd: python src/utils/xml2csv.py data/data.xml data/data.csv
    deps:
    - data/data.xml
    - src/utils/xml2csv.py
    outs:
    - data/data.csv
  process_data:
    cmd: python src/utils/process_data.py data/data.csv data/processed_data.csv
    deps:
    - data/data.csv
    outs:
    - data/processed_data.csv
  train_model:
    cmd: python src/utils/train_model.py data/processed_data.csv models/model.pkl
    deps:
    - data/processed_data.csv
    outs:
    - models/model.pkl
    metrics:
    - metrics.json:
        cache: false
